### ISSUE TITLE
Add meta data to output contexts

### ISSUE THREAD

**Issue by JetXu-LLM** [JetXu-LLM/llama-github#2]
Currently, the `retrieve_context` function in the `llama-github` library returns a list of relevant context strings based on the provided query. However, it would be beneficial to include additional meta data, such as the URL of the source code or documentation, along with each context string. This enhancement will provide more context and make it easier for users to trace back the origin of the retrieved information.

Tasks:
1. Modify the `retrieve_context` function to include meta data, such as the URL, alongside each context string.
2. Update the return type of `retrieve_context` to accommodate the meta data, e.g., using a dictionary or a custom object.
3. Ensure that the meta data is correctly populated during the retrieval process.
4. Update the relevant documentation and docstrings to reflect the changes in the function's input and output.
5. Add unit tests to verify the correctness of the meta data retrieval and association with the context strings.

Skill level: Beginner
Language: Python

If you have any questions or need further clarification, feel free to ask! We appreciate your contribution to enhancing the `llama-github` library.

**Comment by balachander712** [comment]
hi @JetXu-LLM I'd like to take this up

**Comment by JetXu-LLM** [comment]
> hi @JetXu-LLM I'd like to take this up

Hi @balachander712 , thanks a lot for your interest in contributing to llama-github! We really appreciate you stepping up to work on this issue. Feel free to ask any questions as you explore the codebase and work on a solution - I'm happy to provide guidance and context wherever needed.

I'll go ahead and assign this issue to you. Please let me know if you need any additional information or have any thoughts you'd like to discuss. We greatly value all contributions and look forward to collaborating with you on this!

**Comment by balachander712** [comment]
Hi, @JetXu-LLM is this the format that you expect the function to return?
```
[
	{
		'context': 'some_context_string',
		'url': 'relevant_url_1;'
	},
	{
		'context': 'some_context_string',
		'url': 'relevant_url_2;'
	},
	{
		'context': 'some_context_string',
		'url': 'relevant_url_3;'
	},
]
```

If yes, you can check what the `retrieve_context` function would return for the query `"How to create a NumPy array in Python?"` here :- https://pastebin.com/iNY5NW1m

I can go ahead and complete this enhancement if I get a thumbs up from you or please let me know if there are any suggestions that you might have.

**Comment by balachander712** [comment]
Hi @JetXu-LLM 
Sorry for the delayed response.
Please have a look at this PR: https://github.com/JetXu-LLM/llama-github/pull/15
and let me know your comments.

**Comment by JetXu-LLM** [comment]
Hi @balachander712,

Thank you for your PR! I have merged your changes, and the implementation looks great. We really appreciate your contribution to the project.

If you have any other suggestions or encounter any issues, please feel free to raise them. We highly value the participation and support of every contributor.

Thanks again, and I look forward to collaborating with you in the future!

Best regards,  
Jet Xu
