### ISSUE TITLE
Eliminate the warning during retrieve context call

### ISSUE THREAD

**Issue by JetXu-LLM** [JetXu-LLM/llama-github#3]
When calling the `retrieve_context` function in the `llama-github` library, a warning message is occasionally displayed in the console. This warning message may be related to deprecated usage or potential issues within the library's dependencies. The goal of this issue is to investigate the cause of the warning and eliminate it to provide a cleaner and more user-friendly experience.

Steps to Reproduce:
1. Install the `llama-github` library following the installation guidelines.
2. Use the `retrieve_context` function with a valid query and other required parameters.
3. Observe the warning message displayed in the console.

Tasks:
1. Investigate the source of the warning message by examining the library's codebase and its dependencies.
2. Identify the specific line or section of code that triggers the warning.
3. Analyze the warning message and determine the appropriate course of action to resolve it.
4. Implement the necessary changes to eliminate the warning, ensuring that the functionality of the library remains unaffected.
5. Test the modified code thoroughly to verify that the warning no longer appears and that the `retrieve_context` function behaves as expected.
6. Update the relevant documentation, including any release notes or changelog, to mention the resolved warning.

Skill level: Beginner
Language: Python

If you encounter any difficulties or have questions during the process, don't hesitate to reach out for assistance. We value your effort in improving the `llama-github` library's user experience.

**Comment by balachander712** [comment]
@JetXu-LLM hi, i'd like to take this up

**Comment by JetXu-LLM** [comment]
> @JetXu-LLM hi, i'd like to take this up

Hi @balachander712 , thanks a lot for your interest in contributing to llama-github! We really appreciate you stepping up to work on this issue. Feel free to ask any questions as you explore the codebase and work on a solution - I'm happy to provide guidance and context wherever needed.

I'll go ahead and assign this issue to you. Please let me know if you need any additional information or have any thoughts you'd like to discuss. We greatly value all contributions and look forward to collaborating with you on this!
