### ISSUE TITLE
Implement answer_with_context method for direct query-based answers

### ISSUE THREAD

**Issue by JetXu-LLM** [JetXu-LLM/llama-github#6]
Currently, the `GithubRAG` class in the `llama-github` library provides a `retrieve_context` method that retrieves relevant context based on a user's query. However, users often need a more straightforward way to obtain direct answers to their questions without explicitly handling the context retrieval process. To enhance the usability and convenience of the library, we propose adding an `answer_with_context` method to the `GithubRAG` class.

The `answer_with_context` method should accept a user's query and an optional `contexts` parameter. If the `contexts` parameter is not provided, the method should internally call the `retrieve_context` method to obtain the relevant context based on the user's query. Once the context is available, the method should invoke the `self.rag_processor.llm_handler.ainvoke()` method to generate the final answer based on the retrieved context.

Tasks:
1. Design the interface for the `answer_with_context` method, including the method signature and parameter definitions.
2. Implement the logic to check if the `contexts` parameter is provided. If not, call the `retrieve_context` method to obtain the relevant context based on the user's query.
3. Integrate the `self.rag_processor.llm_handler.ainvoke()` method to generate the final answer based on the retrieved or provided context.
4. Handle any necessary error handling and edge cases, such as empty context or invalid queries.
5. Write unit tests to verify the functionality of the `answer_with_context` method, covering different scenarios such as providing context explicitly and relying on the internal context retrieval.
6. Update the library's documentation, including the API reference and usage examples, to showcase the new `answer_with_context` method and its usage.
7. Provide clear and concise inline comments within the implemented code to explain the purpose and functionality of each section.
8. Ensure that the implementation follows the coding style and best practices maintained in the `llama-github` library.
9. Test the `answer_with_context` method thoroughly with various queries and context scenarios to ensure its robustness and reliability.

Skill level: Intermediate
Language: Python

By implementing the `answer_with_context` method, we aim to provide a more user-friendly and efficient way for users to obtain direct answers to their queries without the need to manually handle context retrieval. This enhancement will improve the overall user experience and make the `llama-github` library more versatile and convenient to use.

If you have any suggestions, ideas, or concerns regarding the implementation or design of the `answer_with_context` method, please share them in the comments. We value your feedback and collaboration in making this feature addition successful.

Let's work together to enhance the capabilities of the `llama-github` library and provide a smoother experience for our users!

**Comment by rishatl** [comment]
Hi @JetXu-LLM I got something to try and implement, can you take a look?

**Comment by JetXu-LLM** [comment]
> Hi @JetXu-LLM I got something to try and implement, can you take a look?

Hi @rishatl,

Thank you for your contribution and for implementing the `answer_with_context` method. I appreciate your effort and dedication to enhancing the llama-github library.

I am currently occupied with other tasks but will make sure to review your implementation thoroughly over the weekend. I will provide you with detailed feedback as soon as possible.

Thank you for your patience and understanding 🙂

Best regards,  
JetXu
